# Echidna configuration for D-Loop Protocol
testMode: assertion
testLimit: 10000
corpusDir: echidna-corpus
coverage: true
seqLen: 100
shrinkLimit: 5000
contractAddr: "0x00a329c0648769A73afAc7F9381E08FB43dBEA72"
deployer: "0x30000"
sender: ["0x10000", "0x20000", "0x30000"]
multi-abi: true
filterFunctions: []
filterBlacklist: false
cryticArgs: ["--solc-remaps", "@openzeppelin/=node_modules/@openzeppelin/"]
